FROM python:3.13-slim

WORKDIR /app

# Install Node.js, GCC and G++
RUN apt-get update && apt-get install -y \
    curl \
    gcc \
    g++ \
    make \
    && curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get install -y nodejs \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create non-root user
RUN useradd -m sandboxuser

# Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

USER sandboxuser

ENV PYTHONUNBUFFERED=1

CMD ["bash"]


# initial python implementation

# FROM python:3.13.0-slim

# WORKDIR /app

# # Create non-root user
# RUN useradd -m sandboxuser

# # Install dependencies (system-wide or allowed ones)
# COPY requirements.txt /app/requirements.txt
# RUN pip install --no-cache-dir -r requirements.txt

# # Switch to non-root
# USER sandboxuser

# ENV PYTHONUNBUFFERED=1

# # Default command (main.py will be mounted at runtime)
# CMD ["python", "main.py"]