"""add static grading rules

Revision ID: 2a5001f8840c
Revises: 
Create Date: 2026-07-26 15:19:29.544715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

 
# revision identifiers, used by Alembic.
revision: str = '2a5001f8840c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.create_table(
        'question_static_rules',
        sa.Column('rule_id', sa.Integer(), nullable=False),
        sa.Column('question_id', sa.Integer(), nullable=False),
        sa.Column('rule_type', sa.String(), nullable=False),
        sa.Column('expected_value', sa.Text(), nullable=True),
        sa.Column('weight', sa.Float(), nullable=False),
        sa.Column('required', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['question_id'],
            ['questions.question_id'],
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('rule_id'),
    )

    with op.batch_alter_table(
        'question_static_rules',
        schema=None,
    ) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_question_static_rules_question_id'),
            ['question_id'],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f('ix_question_static_rules_rule_id'),
            ['rule_id'],
            unique=False,
        )

    with op.batch_alter_table(
        'questions',
        schema=None,
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                'language',
                sa.String(),
                nullable=False,
                server_default='python',
            )
        )
        batch_op.add_column(
            sa.Column(
                'functional_weight',
                sa.Float(),
                nullable=False,
                server_default='80',
            )
        )
        batch_op.add_column(
            sa.Column(
                'static_weight',
                sa.Float(),
                nullable=False,
                server_default='20',
            )
        )
        batch_op.alter_column(
            'exam_id',
            existing_type=sa.INTEGER(),
            nullable=False,
        )
        batch_op.alter_column(
            'title',
            existing_type=sa.VARCHAR(),
            nullable=False,
        )
        batch_op.alter_column(
            'description',
            existing_type=sa.TEXT(),
            nullable=False,
        )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('exam_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('static_weight')
        batch_op.drop_column('functional_weight')
        batch_op.drop_column('language')

    with op.batch_alter_table('question_static_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_static_rules_rule_id'))
        batch_op.drop_index(batch_op.f('ix_question_static_rules_question_id'))

    op.drop_table('question_static_rules')
    # ### end Alembic commands ###
